# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAIV41Lm7OjA6aGvoh8yJTR8DbtzLmqv
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from PIL import Image

# การตั้งค่าหน้าเว็บ
st.set_page_config(page_title="Project IS 2568", layout="wide")

# เมนู Sidebar สำหรับเลือกหน้า [cite: 14]
page = st.sidebar.selectbox("เลือกหน้าเว็บ", ["หน้าหลัก", "คำอธิบายโมเดล ML", "หน้าทดสอบโมเดล ML", "คำอธิบายโมเดล NN", "หน้าทดสอบโมเดล NN"])

# --- ฟังก์ชันสำหรับโหลดโมเดล (ต้องทำการ Save โมเดลไว้ก่อน) ---
# @st.cache_resource
# def load_ml_model():
#     return pickle.load(open('ensemble_model.pkl', 'rb'))

# @st.cache_resource
# def load_nn_model():
#     return load_model('cifar10_model.h5')

# --- หน้าทดสอบโมเดล 1: Machine Learning (Stroke Prediction) [cite: 18] ---
if page == "หน้าทดสอบโมเดล ML":
    st.header("🧠 ทดสอบระบบพยากรณ์โรคหลอดเลือดสมอง")
    st.write("กรุณากรอกข้อมูลเพื่อตรวจสอบความเสี่ยง [cite: 24]")

    col1, col2 = st.columns(2)
    with col1:
        age = st.number_input("อายุ (Age)", min_value=0, max_value=120, value=25)
        avg_glucose = st.number_input("ระดับน้ำตาลเฉลี่ย (Avg Glucose Level)", value=100.0)
        bmi = st.number_input("ดัชนีมวลกาย (BMI)", value=25.0)

    with col2:
        gender = st.selectbox("เพศ", ["Male", "Female"])
        hypertension = st.selectbox("โรคความดันโลหิตสูง", ["มี", "ไม่มี"])
        heart_disease = st.selectbox("โรคหัวใจ", ["มี", "ไม่มี"])

    if st.button("ทำนายผล (Predict)"):
        # ตัวอย่างการเตรียมข้อมูล (ต้องตรงกับตอน Train)
        # 1. แปลงค่า Input เป็นตัวเลข
        # 2. ใส่ข้อมูลลงใน DataFrame และเข้าโมเดล
        # result = ml_model.predict(input_data)

        st.success("ประมวลผลสำเร็จ!")
        st.write("ผลการทำนาย: **ไม่มีความเสี่ยง** (ตัวอย่าง)") # แสดงผลตามค่าจากโมเดล

# --- หน้าทดสอบโมเดล 2: Neural Network (CIFAR-10) [cite: 18] ---
elif page == "หน้าทดสอบโมเดล NN":
    st.header("🖼️ ทดสอบระบบจำแนกรูปภาพ (CIFAR-10)")
    st.write("อัปโหลดรูปภาพเพื่อจำแนกประเภท (เช่น แมว, สุนัข, รถยนต์) [cite: 24]")

    uploaded_file = st.file_uploader("เลือกไฟล์รูปภาพ...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='รูปภาพที่อัปโหลด', use_container_width=True)

        # Pre-processing รูปภาพให้เป็น $32 \times 32$
        img_resized = image.resize((32, 32))
        img_array = np.array(img_resized) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        if st.button("จำแนกรูปภาพ"):
            # prediction = nn_model.predict(img_array)
            # class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
            st.info(f"ผลการจำแนก: **Airplane** (ตัวอย่าง)")

# --- หน้าอื่นๆ (อธิบายโมเดล) [cite: 15, 16] ---
elif "คำอธิบาย" in page:
    st.header(page)
    st.markdown("### ทฤษฎีและแนวทางการพัฒนา [cite: 16]")
    st.write("- อธิบายขั้นตอนการทำ Data Cleaning [cite: 16]")
    st.write("- อธิบายทฤษฎีอัลกอริทึมที่ใช้ [cite: 16]")
    st.write("- แหล่งอ้างอิง: [cite: 17]")

else:
    st.title("ระบบวิเคราะห์ข้อมูลด้วย Machine Learning และ Neural Network")
    st.write("โปรเจครายวิชา IS 2568 [cite: 1]")